# Generated by Django 4.0.1 on 2022-01-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_username_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
