# Generated by Django 4.0.1 on 2022-01-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
