# Generated by Django 4.0.1 on 2022-01-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='upvotes_count',
        ),
    ]
