# Generated by Django 4.0.1 on 2022-01-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_answer_created_at_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
