# Generated by Django 4.0.1 on 2022-01-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_answer_text_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondepartment',
            name='department',
            field=models.CharField(choices=[('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('DATA SCIENCE', 'DATA SCIENCE'), ('ELECTRONICS', 'ELECTRONICS'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL'), ('OTHER', 'OTHER')], max_length=30),
        ),
    ]
